### ISSUE TITLE
Copy a collection from one environment to another environment

### ISSUE THREAD

**Issue by CAtSG** [kontent-ai/backup-manager-js#27]
### Motivation

Our content editors upload content (adding new collections) to the Production environment in advance of our design team working on the layout/styling.  The design team works off the Development environment so they can workout the layouts and tweak the styling.  

Currently, we would clone the Production environment (with the newly added collections) to create a new Development environment so the design team can work off the latest content.   The cloning process can take about a hour and it will take longer as we add in more content.

### Proposed solution

It would be useful to have a feature where a collection can be copied from one environment to another environment.

**Comment by Enngage** [comment]
Hi @CAtSG,

Thank you for submitting an issue here!

Is there any reason you cannot use the `canImport` configuration option to limit what gets imported? See example at https://github.com/kontent-ai/backup-manager-js#restore-in-code

For example, to import only content items in certain collection you could use the `contentItem` config option such as:

```
  contentItem: item => item.collection.id === 'yourCollectionId'
```

Similarly, you can control every object that gets imported.

**Comment by Enngage** [comment]
Hi @CAtSG,

Sorry for a bit late comment (I missed it :-)). 

I see, but unfortunately that's a bit outside of my scope and scope of this open source tool :) If you really want this feature I would recommend to get in touch with your Customer Success Manager (or Sales manager) and let him / her know that this feature is really important to you. This will in turn help our product managers prioritize certain things.
