### ISSUE TITLE
To restore workflow step of items in ImportService

### ISSUE THREAD

**Issue by jheelbharambe** [kontent-ai/backup-manager-js#30]
### Motivation

Why is this feature required? What problems does it solve?

As there can be multiple workflow steps associated with a project and localisation flow depends on the workflow step of an item, we request you to add this to your backup and restore functionality. Additionally if the content items are archived and not used anymore, having redundant content items can prove problematic.

### Proposed solution

An ideal solution for the above problems.

Ideally, during backup the workflow step of each item should also be preserved in the zip file created and restored from the file.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Enngage** [comment]
Hi @jheelbharambe,

I've added support for exporting workflows and preserving workflow steps of language variants in version `4.0.0`. We have rebranding packages so you can now find it under new name - see https://www.npmjs.com/package/@kontent-ai/backup-manager

Preserving workflow is a bit more complex than I thought, so please try it and let me know if you encounter some issues.

**Comment by jheelbharambe** [comment]
Thanks for providing a solution for this! I will try it out and revert back to you :)

**Comment by jheelbharambe** [comment]
The changes seem to be working fine! Thanks a lot!
