### ISSUE TITLE
Plus sign in asset file name causes 404 during backup restore

### ISSUE THREAD

**Issue by astef-trilogy** [kontent-ai/backup-manager-js#32]
### Brief bug description

I did an export from one project, then tried to import it to another project, and it failed with 404 during POST of one of the assets, which has a `"file_name": "Workflows+widget.png"`.

I repeated several times, but it didn't help.

Then I deleted this object manually from `assets.json`, cleaned project and started import again. It failed again for another asset: `"file_name": "high-res+Loren.png"` with same http status. 

Then I removed all 7 assets with "+" char in names, and all assets has been successfully imported (565 of them).

I think it's quite likely this problem exists for the specific character in file name.

I'm using CLI on Windows 10, node v16.13.2: `npx kbm --config=restore-staging-config.json`

I also reproduced the same problem in https://kentico.github.io/kontent-template-manager . When I've done this, I copied the failed request and tried to execute it a few times. Problem reproduced each time.

**Comment by Enngage** [comment]
Hi @astef-trilogy,

This turned out to be an issue with the REST API rather than this tool. AFAIK it should be fixed now ;)
