### ISSUE TITLE
Request for adding `max-http-header-size` option to `ExportService` class

### ISSUE THREAD

**Issue by yashashree-gangavane** [kontent-ai/backup-manager-js#36]
### Motivation

I request you to add `max-http-header-size` option  to the `ExportService` class, so that I do not get **Header overflow exception** when I try to backup projects with large amount of content.

### Proposed solution

`ExportService` class accepts `max-http-header-size` option.

**Comment by Enngage** [comment]
This can be solved with Node.js, have a look at readme -> https://github.com/kontent-ai/backup-manager-js#im-getting-header-overflow-exception
