### ISSUE TITLE
`kbm export` command accepts `--projectId` instead of '--environmentId`

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/backup-manager-js#38]
### Brief bug description
The `kbm export` command should accept `--environmentId,` but currently accepts `--projectId` instead. [`IExportConfig`](https://github.com/kontent-ai/backup-manager-js/blob/1ed3a4447adf6470ac5b62f7e091525c9ba6363c/lib/export/export.models.ts#L18C1-L25C2) has the correct attribute on github but the package itself still shows `projectId` https://www.npmjs.com/package/@kontent-ai/backup-manager/v/4.1.0?activeTab=code

I think maybe this is caused by a failed build or something like that but I'm not sure. 

### Repro steps

Install latest version of kbm
Run kbm command with `--environmentId`

### Expected behavior
Successful export

### Actual Behavior
The export fails with the following error `Error: Project id was not provided`

**Comment by Enngage** [comment]
Yeah, this is because we have not released an updated version. We'll release it soon :)

**Comment by Nickm615** [comment]
@Enngage I think this needs to be reopened, I'm still seeing the same issue after deleting & reinstalling package in spite of the release. It seems like the npm registry is not updated maybe?

**Comment by JiriLojda** [comment]
The new version wasn't released until yesterday. Can you please check it now?
