### ISSUE TITLE
Error while restoring the packages 

### ISSUE THREAD

**Issue by uttam-addact** [kontent-ai/backup-manager-js#40]
### Brief bug description

The content Item is not getting imported in other projects while any referenced images are there?

### Repro steps

1. create simple content items using the assets field type.
2. Create a backup of that project
3. try to restore that package to any clean instance

### Expected behavior
The referenced media items also should be imported.

### Screenshots
https://prnt.sc/RLzVzx2FBr7W

**Comment by guillaumeogier** [comment]
Hello,

Do you find a work around or a fix for this ?

**Comment by Enngage** [comment]
Should be fixed in `4.2.1`
