### ISSUE TITLE
`--restore` command is skipping some assets, leading to a validation error due to a missing asset.

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/backup-manager-js#41]
### Brief bug description

`--restore` command is skipping some assets, leading to a validation error due to a missing asset.

### Repro steps

1. Use `--clean` command to create empty target environment
2. Use `--restore` command with the project backup folder (@JiriLojda I can provide you with the data)
3. Compare listed assets in backup folder to the list of uploaded assets in the log and see many are missing.
4. Import fails due to a bad asset reference caused by the missing assets

### Expected behavior

The manager should add all assets from the backup folder

### Test environment
node v18.16.0
npm v9.6.4
@kontent-ai/backup-manager@4.2.0
@kontent-ai/cli@0.8.1

### Additional context

Likely related issue: https://github.com/kontent-ai/backup-manager-js/issues/40

**Comment by Enngage** [comment]
Should be fixed in 4.2.1
